
// 消息发送状态
export const SUCCESS = 'SUCCESS';
export const ERROR = 'ERROR';
export const SENDING = 'SENDING';

// 文本消息发送
export const SEND_TEXT_MESSAGE_SUCCESS = 'SEND_TEXT_MESSAGE_SUCCESS';
export const SEND_TEXT_MESSAGE_ERROR = 'SEND_TEXT_MESSAGE_ERROR';
export const SEND_TEXT_MESSAGE = 'SEND_TEXT_MESSAGE';


// 文本图片发送
export const SEND_IMAGE_MESSAGE_SUCCESS = 'SEND_IMAGE_MESSAGE_SUCCESS';
export const SEND_IMAGE_MESSAGE_ERROR = 'SEND_IMAGE_MESSAGE_ERROR';
export const SEND_IMAGE_MESSAGE_PROGRESS = 'SEND_IMAGE_MESSAGE_PROGRESS';
export const SEND_IMAGE_MESSAGE = 'SEND_IMAGE_MESSAGE';
