
// 消息发送状态
export const SUCCESS = 'SUCCESS';
export const ERROR = 'ERROR';
export const SENDING = 'SENDING';

// 消息类型
export const TEXT_MESSAGE = 'TEXT_MESSAGE';
export const IMAGE_MESSAGE = 'IMAGE_MESSAGE';

// 文本消息发送
export const SEND_TEXT_MESSAGE_SUCCESS = 'SEND_TEXT_MESSAGE_SUCCESS';
export const SEND_TEXT_MESSAGE_ERROR = 'SEND_TEXT_MESSAGE_ERROR';
export const SEND_TEXT_MESSAGE = 'SEND_TEXT_MESSAGE';


// 文本图片发送
export const SEND_IMAGE_MESSAGE_SUCCESS = 'SEND_IMAGE_MESSAGE_SUCCESS';
export const SEND_IMAGE_MESSAGE_ERROR = 'SEND_IMAGE_MESSAGE_ERROR';
export const SEND_IMAGE_MESSAGE_PROGRESS = 'SEND_IMAGE_MESSAGE_PROGRESS';
export const SEND_IMAGE_MESSAGE = 'SEND_IMAGE_MESSAGE';


//加载更多数据
export const LOAD_MORE_MESSAGE_SUCCESS = 'LOAD_MORE_MESSAGE_SUCCESS';
export const LOAD_MORE_MESSAGE_ERROR = 'LOAD_MORE_MESSAGE_ERROR';
export const LOAD_MORE_MESSAGE_REQUEST = 'LOAD_MORE_MESSAGE_REQUEST';
